// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulmoiotecdqflqukzubk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsbW9pb3RlY2RxZmxxdWt6dWJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjkzNDQsImV4cCI6MjA1ODg0NTM0NH0.4FgVt6J75q4UvdlUR3VWAAE-mfL6P_cWrg53lU8HElc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);